# Use an official OpenJDK runtime as the base image
FROM openjdk:17

# Set the working directory in the container
#WORKDIR /app

# Copy the Spring Boot application JAR file into the container
COPY target/motorsports.jar motorsports.jar

# Expose the port on which your Spring Boot application runs
EXPOSE 8080

# Specify the command to run your Spring Boot application when the container starts
CMD ["java", "-jar", "motorsports.jar"]
